version: '3'
services:
  server:
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile.dev
    image: core-ui-nginx
    ports:
      - '18104:80' # Connect localhost 18104 port to container 80 port
    links: # Link services to access http://react and http://deepdetect inside the container
      - deepdetect:deepdetect
      - react:react
    volumes:
      - /data1/core_ui:/opt/platform
  react:
    build:
      context: ../.
      dockerfile: docker/react/Dockerfile.dev
    image: core-ui-react
    environment:
      - NODE_ENV=development
    volumes: # For webpack dev server to use our local files
      - ./..:/usr/src/react
    ports:
      - '3000:3000' # For docker to now where to redirect HMR queries
  deepdetect:
    build:
      context: ../.
      dockerfile: docker/deepdetect/Dockerfile.dev
    image: core-ui-deepdetect
    ports:
      - '8080'
    volumes:
      - /data1/core_ui:/opt/platform
